CREATE table BANKS(
	BNK_ID INTEGER,
	BNK_NAME VARCHAR(50),
	BNK_COUNTRY VARCHAR(50),
	BNK_SWIFTCODE VARCHAR(11),
	PRIMARY KEY (BNK_ID));

CREATE table SWIFTCODES(
	SC_ID INTEGER,
	SC_BANKID INTEGER,
	SC_CODE VARCHAR(11),
	PRIMARY KEY (SC_ID),
	FOREIGN KEY (SC_BANKID) REFERENCES BANKS(BNK_ID));

INSERT INTO BANKS (BNK_ID,BNK_NAME,BNK_COUNTRY,BNK_SWIFTCODE)
	VALUES 
	('1','WFB BANK, INC.','United States',NULL),
	('2','H.D.F.C. BANK','India',NULL);

INSERT INTO SWIFTCODES(SC_ID,SC_BANKID,SC_CODE)
	VALUES 
	('1','1','FDACPREFM'),
	('2','2','ASDFAGYT');

UPDATE BANKS SET BNK_COUNTRY=UPPER(BNK_COUNTRY);
UPDATE BANKS SET BNK_NAME=REPLACE(BNK_NAME,'.','');
UPDATE BANKS SET BNK_NAME=REPLACE(BNK_NAME,',','');
UPDATE BANKS SET BNK_SWIFTCODE=(SELECT SC_CODE FROM SWIFTCODES WHERE SWIFTCODES.SC_BANKID = BANKS.BNK_ID);

