CREATE TABLE COUNTRIES(
	CTRY_ID INTEGER PRIMARY KEY,
	CTRY_NAME VARCHAR(50));

INSERT INTO COUNTRIES
VALUES
	(1,'INDIA'),
	(2,'IRELAND'),
	(3,'SOUTH KOREA');

CREATE TABLE WORKING_CENTERS(
	WC_ID INTEGER PRIMARY KEY,
	WC_NAME VARCHAR(50),
	WC_ADRESS VARCHAR(50),
	WC_COUNTRY_ID INTEGER);

INSERT INTO WORKING_CENTERS
VALUES
	(1,'EUROPE BRANCH','13, WELSH DRIVE, DUBLIN',2),
	(2,'ASIA PACIFIC BRANCH','13298, KING CIRCLE, BUSAN',3);

CREATE TABLE EMPLOYEES(
	EMP_ID INTEGER PRIMARY KEY,
	EMP_FIRST_NAME VARCHAR(50),
	EMP_LAST_NAME VARCHAR(50),
	EMP_BIRTH_DATE date,
	EMP_COUNTRY_ORIGIN_ID INTEGER);
	
INSERT INTO EMPLOYEES
VALUES
	(1,'RONALD','FRIED','1998-12-18',2),
	(2,'TYLER','ALBIES','1990-12-12',NULL),
	(3,'DANSBY','RILEY','2002-04-13',2),
	(4,'FREDDIE','SWANSON','1993-09-30',NULL),
	(5,'LUKE','FREEMAN','1995-06-04',3);

CREATE TABLE EMPLOYEES_WORKING_CENTER(
	EWC_EMPLOYEE_ID INTEGER,
	EWC_WORKING_CENTER_ID INTEGER,
	EWC_START_DATE DATE);
	
INSERT INTO EMPLOYEES_WORKING_CENTER
VALUES
	(1,1,'2019-05-15'),
	(2,2,'2015-05-15'),
	(3,1,'2020-02-15'),
	(4,2,'2019-11-15'),
	(5,1,'2018-05-15');


SELECT DISTINCT 
CTRY_NAME as PAISES,
(SELECT COUNT(*) FROM EMPLOYEES E INNER JOIN EMPLOYEES_WORKING_CENTER EWC WHERE EWC.EWC_EMPLOYEE_ID = E.EMP_ID AND
julianday('now') - Julianday(EWC.EWC_START_DATE) > 365 AND
(CASE 
	WHEN E.EMP_COUNTRY_ORIGIN_ID IS NULL 
	THEN (SELECT WC.WC_COUNTRY_ID
		FROM WORKING_CENTERS WC
		INNER JOIN EMPLOYEES_WORKING_CENTER EWC ON EWC.EWC_WORKING_CENTER_ID = WC.WC_ID
		WHERE E.EMP_ID = EWC_EMPLOYEE_ID)
	ELSE E.EMP_COUNTRY_ORIGIN_ID
END) 

= COUNTRIES.CTRY_ID) 
AS CANTIDAD_EMBAJADORES

FROM COUNTRIES WHERE CANTIDAD_EMBAJADORES > 1
ORDER BY CANTIDAD_EMBAJADORES DESC , paises asc;